dist: precise
sudo: false

jdk:
  - oraclejdk7

env:
  - TEST=java

script:
  - 'if [[ $TEST = java ]]; then mvn test -Dsurefire.useFile=false; fi'

after_success:
  - bash <(curl -s https://codecov.io/bash)
